package pt.kr_eddie.pggj17.level;

public enum Tile {
	AIR(false),
	SOLID(true)
	;
	
	public boolean solid;
	
	Tile(boolean solid) {
		this.solid = solid;
	};
	
	public static Tile TILESET[] = {
/*			0		1		2		3		4		5		6		7		8		9		10		11		12		13		14		15	*/
/*00*/		SOLID,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*01*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*02*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*03*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*04*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*05*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*06*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*07*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*08*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*09*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*10*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*11*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*12*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*13*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*14*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,
/*15*/		AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR,	AIR
	};
}